using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Sage200Microservice.Data.Migrations
{
    /// <inheritdoc />
    // Name generated by 'dotnet ef migrations add AddTransactionAttempts'
    public partial class AddTransactionAttemptsUpdates : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TransactionAttempts",
                schema: "dbo", // Explicitly using dbo schema
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CorrelationId = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: false),
                    ReceivedTimestamp = table.Column<DateTime>(type: "datetime2", nullable: false, defaultValueSql: "SYSUTCDATETIME()"),
                    SourceSystem = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    TriggeringEventId = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: false),
                    EntityType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false), // Stores enum name as string
                    Payload = table.Column<byte[]>(type: "varbinary(max)", nullable: true), // For encrypted data
                    ProcessingStatus = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false), // Stores status name as string
                    KafkaTopic = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    KafkaPartition = table.Column<int>(type: "int", nullable: true),
                    KafkaOffset = table.Column<long>(type: "bigint", nullable: true),
                    KafkaMessageKey = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    SiteId = table.Column<string>(type: "nvarchar(64)", maxLength: 64, nullable: true),
                    CompanyId = table.Column<string>(type: "nvarchar(32)", maxLength: 32, nullable: true),
                    IdempotencyKeyHash = table.Column<string>(type: "nvarchar(88)", maxLength: 88, nullable: true), // Matches IdempotencyRecord.KeyHash
                    ExternalRef = table.Column<string>(type: "nvarchar(200)", maxLength: 200, nullable: true),
                    ApiKeyId = table.Column<int>(type: "int", nullable: true), // FK to ApiKeys.Id (int)
                    ProcessingStartedUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    ProcessingCompletedUtc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DurationMs = table.Column<int>(type: "int", nullable: true),
                    AttemptNumber = table.Column<int>(type: "int", nullable: false, defaultValue: 1),
                    RetryCount = table.Column<int>(type: "int", nullable: false, defaultValue: 0),
                    SageUrn = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true), // Matches ExternalIdLink.SageUrn
                    SageId = table.Column<long>(type: "bigint", nullable: true), // Matches ExternalIdLink.SageId
                    ResultCode = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: true),
                    ResultMessage = table.Column<string>(type: "nvarchar(1024)", maxLength: 1024, nullable: true),
                    OriginalHeadersJson = table.Column<string>(type: "nvarchar(4000)", maxLength: 4000, nullable: true) // Capped JSON string
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TransactionAttempts", x => x.Id);
                    // Unique constraint for Kafka messages
                    table.UniqueConstraint("UX_TransactionAttempts_KafkaUnique", x => new { x.KafkaTopic, x.KafkaPartition, x.KafkaOffset })
                         .Annotation("SqlServer:Filter", "[KafkaTopic] IS NOT NULL AND [KafkaPartition] IS NOT NULL AND [KafkaOffset] IS NOT NULL");
                    // Foreign Key to ApiKeys table
                    table.ForeignKey(
                        name: "FK_TransactionAttempts_ApiKeys_ApiKeyId",
                        column: x => x.ApiKeyId,
                        principalSchema: "dbo", // Assuming ApiKeys is also in dbo
                        principalTable: "ApiKeys",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict); // Prevent deleting an ApiKey if attempts reference it
                });

            // --- Indexes ---
            migrationBuilder.CreateIndex(
                name: "IX_TransactionAttempts_CorrelationId",
                schema: "dbo",
                table: "TransactionAttempts",
                column: "CorrelationId");

            migrationBuilder.CreateIndex(
                name: "IX_TransactionAttempts_IdempotencyKeyHash",
                schema: "dbo",
                table: "TransactionAttempts",
                column: "IdempotencyKeyHash",
                filter: "[IdempotencyKeyHash] IS NOT NULL"); // Filtered index

            migrationBuilder.CreateIndex(
                name: "IX_TransactionAttempts_EntityType_SageUrn",
                schema: "dbo",
                table: "TransactionAttempts",
                columns: new[] { "EntityType", "SageUrn" },
                filter: "[SageUrn] IS NOT NULL"); // Filtered index

            migrationBuilder.CreateIndex(
               name: "IX_TransactionAttempts_EntityType_SageId",
               schema: "dbo",
               table: "TransactionAttempts",
               columns: new[] { "EntityType", "SageId" },
               filter: "[SageId] IS NOT NULL"); // Filtered index

            migrationBuilder.CreateIndex(
                name: "IX_TransactionAttempts_SourceSystem_TriggeringEventId",
                schema: "dbo",
                table: "TransactionAttempts",
                columns: new[] { "SourceSystem", "TriggeringEventId" });

            // Filtered index for finding in-flight attempts
            migrationBuilder.CreateIndex(
                name: "IX_TransactionAttempts_ProcessingStatus_InProgress",
                schema: "dbo",
                table: "TransactionAttempts",
                column: "ProcessingStatus",
                filter: "[ProcessingStatus] IN (N'Received', N'Validated', N'SageCallAttempted')"); // Using string literals for status
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "TransactionAttempts",
                schema: "dbo");
        }
    }
}