// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sage200Microservice.Data;

#nullable disable

namespace Sage200Microservice.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250930_AddIdempotencyRecords")]
    partial class AddIdempotencyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Sage200Microservice.Data.Models.IdempotencyRecord", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedUtc")
                    .HasColumnType("datetime2");

                b.Property<DateTime?>("ExpiresUtc")
                    .HasColumnType("datetime2");

                b.Property<string>("KeyHash")
                    .IsRequired()
                    .HasMaxLength(88)
                    .HasColumnType("nvarchar(88)");

                b.Property<string>("RequestHash")
                    .HasColumnType("nvarchar(max)");

                b.Property<long?>("ResourceId")
                    .HasColumnType("bigint");

                b.HasKey("Id");

                b.HasIndex("KeyHash")
                    .IsUnique();

                b.ToTable("IdempotencyRecords");
            });
#pragma warning restore 612, 618
        }
    }
}
